# Generated by Django 5.0 on 2023-12-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Наименование"
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Цена")),
            ],
        ),
    ]
